name: hl-indexer
on:
  workflow_dispatch:
  schedule:
    - cron: "*/30 * * * *"   # every 30 minutes
jobs:
  run-indexer:
    runs-on: ubuntu-latest
    timeout-minutes: 65
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install requests redis websocket-client
      - env:
          REDIS_URL: ${{ secrets.REDIS_URL }}   # MUST MATCH your Dash app URL exactly
          COIN: BTC
          NOTIONAL_THRESHOLD: "100000"         # start at $1M for better capture rate
          DURATION_SECONDS: "1800"              # 30 min per run
          REQUEST_TIMEOUT: "7"
          THROTTLE_SECONDS: "15"
          META_TTL_SECONDS: "14400"             # 4h
          VERBOSE: "0"
        run: python indexer.py
