name: Whale Indexer

on:
  schedule:
    # Every 15 minutes — adjust as you like
    - cron: "*/15 * * * *"
  workflow_dispatch: {}

jobs:
  run-indexer:
    runs-on: ubuntu-latest
    timeout-minutes: 20  # ensure it cannot hang forever
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run indexer
        env:
          # REQUIRED: set this in your repo Settings → Secrets and variables → Actions → New repository secret
          REDIS_URL: ${{ secrets.REDIS_URL }}
          # OPTIONAL: override defaults
          COIN: BTC
          NOTIONAL_THRESHOLD: "10000000"   # 10M
          DURATION_SECONDS: "600"          # 10 minutes of listening
          REQUEST_TIMEOUT: "5"
          THROTTLE_SECONDS: "30"
        run: |
          python indexer.py
